name = 'mybookings-ae2'
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-12-05"
compatibility_flags = [ "nodejs_compat" ]

[vars]
NEXT_PUBLIC_API_URL = "https://24-bookingbackend.example.com/"